package com.alzswell.product.application;
import static com.alzswell.product.api.FinancialProductResponses.*;
import com.alzswell.common.exception.BusinessException;
import com.alzswell.product.api.*;
import java.math.*;
import java.time.LocalDate;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service @Transactional(readOnly=true)
public class FinancialProductService {
 private static final BigDecimal HUNDRED=BigDecimal.valueOf(100),TWELVE=BigDecimal.valueOf(12),TAX_RATE=new BigDecimal("0.154");
 private static final String DEPOSIT_SELECT="""
 select p.product_id,p.institution_id,i.display_name institution_name,p.product_name,p.product_type,p.min_principal,p.max_principal,p.min_term_months,p.max_term_months,p.interest_payment_type,p.summary,p.caution_text,p.status,p.currency,p.data_as_of from deposit_product_snapshot p join financial_institution i on i.institution_id=p.institution_id
 """;
 private static final String LOAN_SELECT="""
 select p.product_id,p.institution_id,i.display_name institution_name,p.product_name,p.product_type,p.min_principal,p.max_principal,p.min_term_months,p.max_term_months,p.min_annual_interest_rate,p.max_annual_interest_rate,p.repayment_method,p.summary,p.caution_text,p.status,p.currency,p.data_as_of from loan_product_snapshot p join financial_institution i on i.institution_id=p.institution_id
 """;
 private final JdbcTemplate jdbc;
 public FinancialProductService(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public DepositProductList depositProducts(){List<DepositProduct> items=jdbc.query(DEPOSIT_SELECT+" where p.status='AVAILABLE' order by p.product_type,p.product_name,p.product_id",this::depositRow);return new DepositProductList(items,items.size(),true,false);}
 public DepositProductDetail depositProduct(UUID id){DepositRow row=ownedDeposit(id);return new DepositProductDetail(row.product(),row.caution(),false,true,false,false);}
 public DepositRateList depositRates(UUID id){ownedDeposit(id);List<DepositRate> items=jdbc.query("select rate_id,tier_code,min_term_months,max_term_months,annual_interest_rate,rate_type,data_as_of from deposit_product_rate_snapshot where product_id=? order by min_term_months,rate_id",(r,n)->new DepositRate(r.getObject("rate_id",UUID.class),r.getString("tier_code"),r.getInt("min_term_months"),r.getInt("max_term_months"),r.getBigDecimal("annual_interest_rate"),r.getString("rate_type"),r.getObject("data_as_of",LocalDate.class)),id);return new DepositRateList(id,items,items.size(),true,false);}
 public InterestSimulation simulateInterest(UUID id,FinancialProductRequests.InterestSimulation command){DepositRow product=ownedDeposit(id);checkRange(command.principalAmount(),command.termMonths(),product.product().minPrincipal(),product.product().maxPrincipal(),product.product().minTermMonths(),product.product().maxTermMonths());List<BigDecimal> rates=jdbc.query("select annual_interest_rate from deposit_product_rate_snapshot where product_id=? and ? between min_term_months and max_term_months order by annual_interest_rate desc,rate_id limit 1",(r,n)->r.getBigDecimal(1),id,command.termMonths());if(rates.isEmpty())throw new BusinessException(FinancialProductErrorCode.RATE_NOT_AVAILABLE);BigDecimal rate=rates.getFirst();boolean installment="INSTALLMENT_SAVINGS".equals(product.product().productType());BigDecimal totalPrincipal=installment?command.principalAmount().multiply(BigDecimal.valueOf(command.termMonths())):command.principalAmount();BigDecimal gross=installment?command.principalAmount().multiply(rate).divide(HUNDRED,12,RoundingMode.HALF_UP).divide(TWELVE,12,RoundingMode.HALF_UP).multiply(BigDecimal.valueOf((long)command.termMonths()*(command.termMonths()+1)/2)).setScale(0,RoundingMode.DOWN):command.principalAmount().multiply(rate).divide(HUNDRED,12,RoundingMode.HALF_UP).multiply(BigDecimal.valueOf(command.termMonths())).divide(TWELVE,0,RoundingMode.DOWN);BigDecimal tax=gross.multiply(TAX_RATE).setScale(0,RoundingMode.DOWN);BigDecimal net=gross.subtract(tax);return new InterestSimulation(id,installment?"MONTHLY_CONTRIBUTION":"LUMP_SUM",command.principalAmount(),command.termMonths(),rate,totalPrincipal,gross,tax,net,totalPrincipal.add(net),"KRW",installment?"MONTHLY_CONTRIBUTION_SIMPLE_INTEREST_V1":"LUMP_SUM_SIMPLE_INTEREST_V1",false,false,true,false,false);}
 public MaturityOptionList maturityOptions(String customerId,UUID holdingId){List<LocalDate> holding=jdbc.query("select maturity_date from customer_deposit_holding_snapshot where customer_id=? and holding_id=?",(r,n)->r.getObject(1,LocalDate.class),customerId,holdingId);if(holding.size()!=1)throw new BusinessException(FinancialProductErrorCode.HOLDING_NOT_FOUND);List<MaturityOption> items=jdbc.query("select option_id,option_code,title,description,display_order from deposit_maturity_option_snapshot where holding_id=? order by display_order,option_id",(r,n)->new MaturityOption(r.getObject("option_id",UUID.class),r.getString("option_code"),r.getString("title"),r.getString("description"),r.getInt("display_order")),holdingId);return new MaturityOptionList(holdingId,holding.getFirst(),items,items.size(),false,true,false,false);}
 public LoanProductList loanProducts(){List<LoanProduct> items=jdbc.query(LOAN_SELECT+" where p.status='AVAILABLE' order by p.product_type,p.product_name,p.product_id",this::loanRow);return new LoanProductList(items,items.size(),true,false);}
 public LoanProductDetail loanProduct(UUID id){LoanRow row=ownedLoan(id);return new LoanProductDetail(row.product(),row.caution(),false,false,true,false,false);}
 public RepaymentSimulation simulateRepayment(UUID id,FinancialProductRequests.RepaymentSimulation command){LoanRow row=ownedLoan(id);LoanProduct p=row.product();checkRange(command.principalAmount(),command.termMonths(),p.minPrincipal(),p.maxPrincipal(),p.minTermMonths(),p.maxTermMonths());if(command.annualInterestRate().compareTo(p.minAnnualInterestRate())<0||command.annualInterestRate().compareTo(p.maxAnnualInterestRate())>0)throw new BusinessException(FinancialProductErrorCode.INPUT_OUT_OF_RANGE);BigDecimal months=BigDecimal.valueOf(command.termMonths());BigDecimal monthlyPrincipal=command.principalAmount().divide(months,0,RoundingMode.DOWN);BigDecimal monthlyRate=command.annualInterestRate().divide(HUNDRED,12,RoundingMode.HALF_UP).divide(TWELVE,12,RoundingMode.HALF_UP);BigDecimal firstInterest=command.principalAmount().multiply(monthlyRate).setScale(0,RoundingMode.HALF_UP);BigDecimal lastPrincipal=command.principalAmount().subtract(monthlyPrincipal.multiply(BigDecimal.valueOf(command.termMonths()-1L)));BigDecimal lastInterest=lastPrincipal.multiply(monthlyRate).setScale(0,RoundingMode.HALF_UP);BigDecimal totalInterest=command.principalAmount().multiply(BigDecimal.valueOf(command.termMonths()+1L)).divide(BigDecimal.valueOf(2),12,RoundingMode.HALF_UP).multiply(monthlyRate).setScale(0,RoundingMode.HALF_UP);return new RepaymentSimulation(id,command.principalAmount(),command.termMonths(),command.annualInterestRate(),p.repaymentMethod(),monthlyPrincipal,monthlyPrincipal.add(firstInterest),lastPrincipal.add(lastInterest),totalInterest,command.principalAmount().add(totalInterest),"KRW","EQUAL_PRINCIPAL_ESTIMATE_V1",false,false,false,true,false,false);}
 private void checkRange(BigDecimal amount,int term,BigDecimal min,BigDecimal max,int minTerm,int maxTerm){if(amount.compareTo(min)<0||amount.compareTo(max)>0||term<minTerm||term>maxTerm)throw new BusinessException(FinancialProductErrorCode.INPUT_OUT_OF_RANGE);}
 private DepositRow ownedDeposit(UUID id){List<DepositRow> rows=jdbc.query(DEPOSIT_SELECT+" where p.product_id=?",this::depositRaw,id);if(rows.size()!=1)throw new BusinessException(FinancialProductErrorCode.PRODUCT_NOT_FOUND);return rows.getFirst();}
 private LoanRow ownedLoan(UUID id){List<LoanRow> rows=jdbc.query(LOAN_SELECT+" where p.product_id=?",this::loanRaw,id);if(rows.size()!=1)throw new BusinessException(FinancialProductErrorCode.PRODUCT_NOT_FOUND);return rows.getFirst();}
 private DepositProduct depositRow(java.sql.ResultSet r,int n)throws java.sql.SQLException{return depositRaw(r,n).product();}
 private DepositRow depositRaw(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new DepositRow(new DepositProduct(r.getObject("product_id",UUID.class),r.getString("institution_id"),r.getString("institution_name"),r.getString("product_name"),r.getString("product_type"),r.getBigDecimal("min_principal"),r.getBigDecimal("max_principal"),r.getInt("min_term_months"),r.getInt("max_term_months"),r.getString("interest_payment_type"),r.getString("summary"),r.getString("status"),r.getString("currency"),r.getObject("data_as_of",LocalDate.class)),r.getString("caution_text"));}
 private LoanProduct loanRow(java.sql.ResultSet r,int n)throws java.sql.SQLException{return loanRaw(r,n).product();}
 private LoanRow loanRaw(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new LoanRow(new LoanProduct(r.getObject("product_id",UUID.class),r.getString("institution_id"),r.getString("institution_name"),r.getString("product_name"),r.getString("product_type"),r.getBigDecimal("min_principal"),r.getBigDecimal("max_principal"),r.getInt("min_term_months"),r.getInt("max_term_months"),r.getBigDecimal("min_annual_interest_rate"),r.getBigDecimal("max_annual_interest_rate"),r.getString("repayment_method"),r.getString("summary"),r.getString("status"),r.getString("currency"),r.getObject("data_as_of",LocalDate.class)),r.getString("caution_text"));}
 private record DepositRow(DepositProduct product,String caution){} private record LoanRow(LoanProduct product,String caution){}
}
