"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { apiRequest, type ApiResponse } from "../lib/api";
import { clearDemoContext, readDemoContext, saveDemoContext, type DemoContext } from "../lib/demo-session";
import { DEMO_REHEARSAL_SCENARIOS, findRehearsalScenario, type DemoRehearsalScenario } from "../lib/demo-rehearsal";
import { createDemoContext, discardDemoSession } from "../lib/demo-workflow";
type Summary={assets:{total:{amount:string}};cashFlow:{monthlyIncome:{amount:string};monthlyExpense:{amount:string}};changeSummary:{openAlertCount:number;summary:string}};
type AlertList={items?:Array<Record<string,unknown>>};
const messageOf=(error:unknown)=>(error as Partial<ApiResponse<unknown>>).message??(error instanceof Error?error.message:"백엔드 연결 상태를 확인해 주세요.");
export function DemoDashboard(){
 const[context,setContext]=useState<DemoContext|null>(null),[summary,setSummary]=useState<Summary|null>(null),[alertCount,setAlertCount]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function load(active:DemoContext){const common={capability:active.capability,demoRunId:active.demoRunId};const[s,a]=await Promise.all([apiRequest<Summary>(`/api/v1/demo/sessions/${active.sessionId}/customers/${active.customerId}/financial-summary`,common),apiRequest<AlertList>(`/api/v1/demo/sessions/${active.sessionId}/customers/${active.customerId}/alerts`,common)]);setSummary(s.body.data);setAlertCount(a.body.data?.items?.length??s.body.data?.changeSummary.openAlertCount??0)}
 useEffect(()=>{const saved=readDemoContext();if(saved){setContext(saved);load(saved).catch(reason=>setError(messageOf(reason))) }},[]);
 async function startDemo(rehearsalScenario?:DemoRehearsalScenario){setLoading(true);setError("");try{const created=await createDemoContext();const next={...created,...(rehearsalScenario?{rehearsalScenario}:{})};saveDemoContext(next);setContext(next);await load(next)}catch(reason){setError(messageOf(reason))}finally{setLoading(false)}}
 async function reset(){if(context)await discardDemoSession(context.sessionId,context.capability);clearDemoContext();setContext(null);setSummary(null);setAlertCount(0);setError("")}
 const money=(value?:string)=>value?`${Number(value).toLocaleString("ko-KR")}원`:"-";
 if(!context)return <><section className="panel hero-panel"><div><p className="muted">합성데이터 기반 안전 체험</p><h2>금융생활 변화 알림을<br/>직접 확인해 보세요.</h2></div><button onClick={()=>void startDemo()} disabled={loading}>{loading?"준비 중…":"자유 체험 시작"}</button></section><section className="panel rehearsal-launch"><div className="section-heading"><div><p className="label">발표 리허설</p><h2>검증할 시나리오를 선택하세요.</h2></div><span className="status-chip">정상 · 주의 · 오탐</span></div><div className="rehearsal-grid">{DEMO_REHEARSAL_SCENARIOS.map((scenario)=><button key={scenario.id} onClick={()=>void startDemo(scenario.id)} disabled={loading}><span>{scenario.label}</span><strong>{scenario.title}</strong><small>{scenario.summary}</small><em>예상 종결: {scenario.expectedState}</em></button>)}</div></section>{error&&<p className="api-error" role="alert">{error}</p>}</>;
 const rehearsal=findRehearsalScenario(context.rehearsalScenario);
 return <>{rehearsal&&<section className="panel rehearsal-status" data-rehearsal-scenario={rehearsal.id}><div><p className="label">{rehearsal.label} 시나리오 진행 중</p><h2>{rehearsal.title}</h2><p>{rehearsal.summary}</p></div><ol>{rehearsal.checkpoints.map((checkpoint,index)=><li key={checkpoint}><span>{index+1}</span>{checkpoint}</li>)}</ol></section>}<section className="summary-strip"><article className="panel"><p className="label">총 금융자산</p><strong>{money(summary?.assets.total.amount)}</strong></article><article className="panel"><p className="label">월 수입</p><strong>{money(summary?.cashFlow.monthlyIncome.amount)}</strong></article><article className="panel"><p className="label">월 지출</p><strong>{money(summary?.cashFlow.monthlyExpense.amount)}</strong></article></section><section className="panel alert-overview"><div><p className="label">최근 변화 알림</p><h2>{alertCount}개의 변화가 발견되었습니다.</h2><p className="muted">{summary?.changeSummary.summary??"고객의 확인이 필요한 금융생활 변화입니다."}</p></div><Link className="primary-button" href="/demo/alerts">알림 확인하기</Link></section><section className="panel alert-overview ai-entry"><div><p className="label">새로운 AI 맞춤 기능</p><h2>나의 의향과 장기 변화를 함께 확인하세요.</h2><p className="muted">AI 의향서 · 30·60·90일 변화 · 쉬운말과 음성 안내</p></div><Link className="primary-button" href="/demo/ai-assistant">AI 금융생활 도우미</Link></section>{error&&<p className="api-error" role="alert">{error}</p>}<button className="secondary-button" onClick={()=>void reset()} disabled={loading}>새 체험 시작</button></>;
}
