"use client";

import { useEffect, useState } from "react";
import { loadAccountWorkspace, type AccountWorkspace } from "../lib/private-banking";
import { restorePrivateCustomerSession, type PrivateCustomerSession } from "../lib/private-financial-products";
import { LoginRequired } from "./PrivateBankingDashboard";

export function PrivateAccountsWorkspace() {
  const [session, setSession] = useState<PrivateCustomerSession | null>(null);
  const [workspace, setWorkspace] = useState<AccountWorkspace | null>(null);
  const [accountId, setAccountId] = useState(""); const [query, setQuery] = useState("");
  const [busy, setBusy] = useState(true); const [error, setError] = useState("");
  useEffect(() => { void restorePrivateCustomerSession().then(async (active) => { setSession(active); const loaded = await loadAccountWorkspace(active); setWorkspace(loaded); setAccountId(loaded.accounts[0]?.accountId ?? ""); }).catch((reason) => setError(message(reason))).finally(() => setBusy(false)); }, []);
  async function reload(nextAccount = accountId, nextQuery = query) { if (!session) return; setBusy(true); setError(""); try { setWorkspace(await loadAccountWorkspace(session, nextAccount || undefined, nextQuery.trim() || undefined)); } catch (reason) { setError(message(reason)); } finally { setBusy(false); } }
  if (!session && busy) return <section className="bank-panel banking-loading"><div className="bank-spinner" /><p>계좌와 거래내역을 불러오고 있습니다.</p></section>;
  if (!session) return <LoginRequired message={error} />;
  if (!workspace) return <section className="bank-panel login-required"><h2>계좌 정보를 불러오지 못했습니다.</h2><p>{error}</p><button className="primary-button" onClick={() => void reload()}>다시 조회</button></section>;
  return <div className="private-accounts-workspace">
    <section className="account-selector bank-panel"><div><p>내 계좌</p><h2>{workspace.accounts.length}개 계좌를 연결했습니다.</h2></div><select value={accountId} onChange={(event) => { setAccountId(event.target.value); void reload(event.target.value, query); }}>{workspace.accounts.map((account) => <option value={account.accountId} key={account.accountId}>{account.institutionName} · {account.displayName} · {account.maskedAccountNumber}</option>)}</select></section>
    <section className="banking-summary-grid account-stats"><article><span>조회 계좌 잔액</span><strong>{won(value(workspace.balance, "currentBalance"))}</strong><small>출금 가능 {won(value(workspace.balance, "availableBalance"))}</small></article><article><span>기간 수입</span><strong className="positive">+{won(workspace.transactionSummary.totalInflow)}</strong><small>{workspace.transactionSummary.transactionCount}건 분석</small></article><article><span>기간 지출</span><strong>-{won(workspace.transactionSummary.totalOutflow)}</strong><small>순현금흐름 {won(workspace.transactionSummary.netCashflow)}</small></article><article><span>정기납부</span><strong>{workspace.recurring.length}건</strong><small>누락 {workspace.missed.length} · 중복 {workspace.duplicates.length}</small></article></section>
    <div className="banking-content-grid account-detail-grid"><section className="bank-panel"><header><div><p>계좌 상세</p><h3>{workspace.accounts.find((item) => item.accountId === accountId)?.displayName ?? "대표 계좌"}</h3></div><span>조회 전용</span></header><dl className="banking-detail-list"><div><dt>계좌 상태</dt><dd>{workspace.accounts.find((item) => item.accountId === accountId)?.accountStatus}</dd></div><div><dt>적용 이율</dt><dd>{value(workspace.interest, "annualInterestRate") || 0}%</dd></div><div><dt>누적 이자</dt><dd>{won(value(workspace.interest, "accruedInterest"))}</dd></div><div><dt>거래명세서</dt><dd>{workspace.statements.length}개</dd></div><div><dt>계좌 제한</dt><dd>{workspace.restrictions.length ? `${workspace.restrictions.length}건 확인 필요` : "없음"}</dd></div><div><dt>반복 거래처</dt><dd>{workspace.recurringCounterparties.length}곳</dd></div></dl></section><section className="bank-panel"><header><div><p>잔액 흐름</p><h3>최근 잔액 추세</h3></div><span>{workspace.balanceHistory.length}개 시점</span></header><div className="balance-history">{workspace.balanceHistory.slice(-10).map((point, index) => <article key={String(point.balanceDate ?? index)}><time>{String(point.balanceDate ?? "-").slice(5)}</time><i style={{ height: `${Math.max(8, value(point, "currentBalance") / Math.max(...workspace.balanceHistory.map((item) => value(item, "currentBalance")), 1) * 100)}%` }} /><strong>{compact(value(point, "currentBalance"))}</strong></article>)}</div></section></div>
    <section className="bank-panel transaction-workspace"><header><div><p>거래내역</p><h3>전체 계좌 통합 검색</h3></div><form onSubmit={(event) => { event.preventDefault(); void reload(accountId, query); }}><input value={query} maxLength={80} onChange={(event) => setQuery(event.target.value)} placeholder="거래처·내용 검색" /><button disabled={busy}>{busy ? "조회 중" : "검색"}</button></form></header><div className="transaction-table"><div className="transaction-table-head"><span>일시</span><span>계좌·내용</span><span>분류</span><span>금액</span><span>잔액</span></div>{workspace.transactions.map((item) => <article key={item.transactionId}><time>{dateTime(item.occurredAt)}</time><p><strong>{item.counterpartyName || item.description}</strong><small>{item.accountDisplayName} · {item.institutionName}</small></p><span>{category(item.category)}</span><b className={item.direction === "CREDIT" ? "positive" : ""}>{item.direction === "CREDIT" ? "+" : "−"}{won(item.amount)}</b><small>{won(item.balanceAfter)}</small></article>)}</div>{!workspace.transactions.length && <div className="empty-block">검색 조건에 맞는 거래가 없습니다.</div>}</section>
    <section className="bank-panel recurring-workspace"><header><div><p>정기납부·구독</p><h3>다가오는 생활비</h3></div><span>실제 납부·해지 없음</span></header><div className="recurring-grid">{workspace.recurring.map((item) => <article key={item.recurringPaymentId}><div><span>{category(item.categoryCode).slice(0, 1)}</span><p><strong>{item.displayName}</strong><small>{item.institutionName} · {item.cadence}</small></p></div><b>{won(item.expectedAmount)}</b><time>{item.nextExpectedDate} 예정</time><em className={item.observationStatus === "ON_TRACK" ? "safe" : "warning"}>{observation(item.observationStatus)}</em></article>)}</div><div className="recurring-alerts"><p><strong>미발생 후보 {workspace.missed.length}건</strong> 평소 예정일과 비교해 확인합니다.</p><p><strong>중복 후보 {workspace.duplicates.length}건</strong> 자동 해지하거나 차단하지 않습니다.</p></div></section>
    {error && <p className="api-error" role="alert">{error}</p>}
  </div>;
}

function value(record: Record<string, unknown> | null, key: string) { return Number(record?.[key] ?? 0); }
function won(value: number) { return `${Number(value ?? 0).toLocaleString("ko-KR")}원`; }
function compact(value: number) { return Intl.NumberFormat("ko-KR", { notation: "compact" }).format(value); }
function dateTime(value: string) { return new Intl.DateTimeFormat("ko-KR", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function category(value: string) { return ({ INCOME: "수입", HOUSING: "주거", UTILITIES: "공과금", COMMUNICATION: "통신", FOOD: "식비", TRANSPORT: "교통", HEALTH: "건강", FINANCE: "금융", SHOPPING: "쇼핑", OTHER: "기타" } as Record<string, string>)[value] ?? value; }
function observation(value: string) { return ({ ON_TRACK: "정상", MISSED_CANDIDATE: "미발생 확인", DUPLICATE_CANDIDATE: "중복 확인" } as Record<string, string>)[value] ?? value; }
function message(reason: unknown) { return reason instanceof Error ? reason.message : "계좌 정보를 불러오지 못했습니다."; }
