"use client";

import { useEffect, useState } from "react";
import { deleteTransferTemplate, evaluateTransfer, loadTransferWorkspace, saveTransferTemplate, type TransferResult, type TransferWorkspace } from "../lib/private-banking";
import { restorePrivateCustomerSession, type PrivateCustomerSession } from "../lib/private-financial-products";
import { LoginRequired } from "./PrivateBankingDashboard";

export function PrivateTransferWorkspace() {
  const [session, setSession] = useState<PrivateCustomerSession | null>(null); const [workspace, setWorkspace] = useState<TransferWorkspace | null>(null);
  const [accountId, setAccountId] = useState(""); const [beneficiaryId, setBeneficiaryId] = useState(""); const [amount, setAmount] = useState(100000); const [purpose, setPurpose] = useState("LIVING_EXPENSE");
  const [templateName, setTemplateName] = useState("자주 보내는 생활비"); const [result, setResult] = useState<{ simulation: TransferResult; validation: TransferResult } | null>(null);
  const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function load(active: PrivateCustomerSession) { const loaded = await loadTransferWorkspace(active); setWorkspace(loaded); setAccountId((current) => current || loaded.accounts[0]?.accountId || ""); setBeneficiaryId((current) => current || loaded.beneficiaries[0]?.beneficiaryId || ""); }
  useEffect(() => { void restorePrivateCustomerSession().then(async (active) => { setSession(active); await load(active); }).catch((reason) => setError(message(reason))); }, []);
  async function evaluate() { if (!session || !accountId || !beneficiaryId) return; setBusy("evaluate"); setError(""); setNotice(""); try { setResult(await evaluateTransfer(session, accountId, beneficiaryId, amount, purpose)); } catch (reason) { setError(message(reason)); } finally { setBusy(""); } }
  async function save() { if (!session) return; setBusy("save"); setError(""); try { await saveTransferTemplate(session, templateName, accountId, beneficiaryId, amount, purpose); await load(session); setNotice("이체 없이 안전한 양식만 저장했습니다."); } catch (reason) { setError(message(reason)); } finally { setBusy(""); } }
  async function remove(templateId: string) { if (!session) return; setBusy(templateId); setError(""); try { await deleteTransferTemplate(session, templateId); await load(session); setNotice("저장 양식을 삭제했습니다. 실제 금융거래에는 영향이 없습니다."); } catch (reason) { setError(message(reason)); } finally { setBusy(""); } }
  if (!session && !error) return <section className="bank-panel banking-loading"><div className="bank-spinner" /><p>이체 확인 정보를 불러오고 있습니다.</p></section>;
  if (!session) return <LoginRequired message={error} />;
  if (!workspace) return <section className="bank-panel login-required"><h2>이체 정보를 불러오지 못했습니다.</h2><p>{error}</p></section>;
  const selectedAccount = workspace.accounts.find((item) => item.accountId === accountId); const beneficiary = workspace.beneficiaries.find((item) => item.beneficiaryId === beneficiaryId);
  return <div className="private-transfer-workspace">
    <section className="transfer-safety"><span>!</span><div><strong>이 화면은 실제 송금을 실행하지 않습니다.</strong><p>회원별 합성 잔액·한도·수취인으로 가능 여부만 미리 확인하고 승인이나 OTP를 만들지 않습니다.</p></div><em>SIMULATION ONLY</em></section>
    <div className="transfer-layout"><section className="bank-panel transfer-form"><header><div><p>안전 이체 확인</p><h2>보낼 내용을 확인해 주세요.</h2></div><span>외부 호출 없음</span></header><label><span>출금 계좌</span><select value={accountId} onChange={(event) => { setAccountId(event.target.value); setResult(null); }}>{workspace.accounts.map((account) => <option value={account.accountId} key={account.accountId}>{account.institutionName} {account.maskedAccountNumber} · {won(account.availableBalance)}</option>)}</select></label><label><span>받는 분</span><select value={beneficiaryId} onChange={(event) => { setBeneficiaryId(event.target.value); setResult(null); }}>{workspace.beneficiaries.map((item) => <option value={item.beneficiaryId} key={item.beneficiaryId}>{item.displayName} · {item.institutionName} {item.maskedAccountReference}</option>)}</select></label><label><span>금액</span><div className="amount-input"><input type="number" min={1} max={100000000} step={10000} value={amount} onChange={(event) => { setAmount(Number(event.target.value)); setResult(null); }} /><b>원</b></div></label><div className="amount-shortcuts">{[10000, 50000, 100000, 1000000].map((value) => <button type="button" key={value} onClick={() => { setAmount(value); setResult(null); }}>+{compact(value)}</button>)}</div><label><span>보내는 목적</span><select value={purpose} onChange={(event) => { setPurpose(event.target.value); setResult(null); }}><option value="LIVING_EXPENSE">생활비</option><option value="FAMILY_SUPPORT">가족 지원</option><option value="BILL_PAYMENT">요금 납부</option><option value="OWN_ACCOUNT">내 계좌 이동</option><option value="OTHER">기타</option></select></label><button className="primary-button" disabled={busy !== "" || !accountId || !beneficiaryId || amount < 1} onClick={() => void evaluate()}>{busy === "evaluate" ? "조건 확인 중…" : "이체 가능 여부 미리 확인"}</button></section>
    <aside className="transfer-side"><section className="bank-panel transfer-limit"><p>오늘의 합성 이체한도</p><strong>{won(workspace.limit.dailyRemainingAmount)}</strong><span>1회 {won(workspace.limit.perTransferLimit)} · 사용 {won(workspace.limit.dailyUsedAmount)}</span><i><b style={{ width: `${Math.min(100, workspace.limit.dailyUsedAmount / Math.max(workspace.limit.dailyLimit, 1) * 100)}%` }} /></i><small>{workspace.limit.dataAsOf} 고정 기준일 · 실제 한도 아님</small></section><section className="bank-panel beneficiary-card"><p>선택한 받는 분</p><div><span>{beneficiary?.displayName.slice(0, 1) || "?"}</span><strong>{beneficiary?.displayName || "수취인을 선택하세요"}</strong><small>{beneficiary?.institutionName} · {beneficiary?.maskedAccountReference}</small></div><dl><div><dt>등록 상태</dt><dd>{beneficiary?.status}</dd></div><div><dt>출금 가능액</dt><dd>{won(selectedAccount?.availableBalance ?? 0)}</dd></div></dl></section></aside></div>
    {result && <section className="bank-panel transfer-result"><header><div><p>모의계산·사전검증 결과</p><h2>{result.validation.allowed ? "조건을 충족했습니다." : "확인이 필요한 조건이 있습니다."}</h2></div><span className={result.validation.allowed ? "safe" : "warning"}>{result.validation.decisionCode || result.simulation.outcomeCode}</span></header><div className="transfer-result-money"><span>예상 출금액<strong>{won(result.simulation.totalDebit ?? amount)}</strong></span><span>예상 수수료<strong>{won(result.simulation.estimatedFee ?? 0)}</strong></span><span>계산 후 가용잔액<strong>{won(result.simulation.projectedAvailableBalance ?? 0)}</strong></span></div><ul>{result.validation.checks.map((check) => <li className={check.passed ? "passed" : "failed"} key={check.checkCode}><span>{check.passed ? "✓" : "!"}</span><p><strong>{check.checkCode}</strong>{check.message}</p></li>)}</ul><div className="no-execution-proof"><b>이체 생성 {String(result.simulation.transferCreated)}</b><b>승인 생성 {String(result.simulation.authorizationCreated)}</b><span>검증 결과는 실제 실행 권한이 아닙니다.</span></div></section>}
    <section className="bank-panel transfer-templates"><header><div><p>저장 이체 양식</p><h2>자주 확인하는 이체</h2></div><span>{workspace.templates.length}개</span></header><div className="template-create"><input value={templateName} maxLength={50} onChange={(event) => setTemplateName(event.target.value)} placeholder="양식 이름" /><button disabled={busy !== "" || !result || !templateName.trim()} onClick={() => void save()}>{busy === "save" ? "저장 중…" : "현재 내용 양식 저장"}</button></div><div className="template-list">{workspace.templates.map((item) => <article key={item.templateId}><span>↗</span><p><strong>{item.templateName}</strong><small>{item.sourceAccountDisplayName} → {item.beneficiaryDisplayName} {item.maskedBeneficiaryAccount}</small></p><b>{won(item.amount)}</b><button disabled={busy !== ""} onClick={() => void remove(item.templateId)}>{busy === item.templateId ? "삭제 중" : "삭제"}</button></article>)}</div>{!workspace.templates.length && <div className="empty-block">저장된 이체 양식이 없습니다.</div>}</section>
    {notice && <p className="workflow-result" role="status">{notice}</p>}{error && <p className="api-error" role="alert">{error}</p>}
  </div>;
}

function won(value: number) { return `${Number(value ?? 0).toLocaleString("ko-KR")}원`; }
function compact(value: number) { return Intl.NumberFormat("ko-KR", { notation: "compact" }).format(value); }
function message(reason: unknown) { return reason instanceof Error ? reason.message : "이체 조건을 확인하지 못했습니다."; }
