package com.alzswell.intent;
import static org.assertj.core.api.Assertions.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;
import com.fasterxml.jackson.databind.*;import java.util.UUID;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.testcontainers.service.connection.ServiceConnection;import org.springframework.dao.DataAccessException;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.test.context.support.WithMockUser;import org.springframework.test.web.servlet.*;import org.testcontainers.containers.PostgreSQLContainer;import org.testcontainers.junit.jupiter.*;
@SpringBootTest @AutoConfigureMockMvc @Testcontainers(disabledWithoutDocker=true)
class FinancialIntentIntegrationTest {static final String C="SYN_CUSTOMER_FIN_MGMT_001";@Container@ServiceConnection static final PostgreSQLContainer<?> P=new PostgreSQLContainer<>("postgres:17-alpine");@Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;
 @BeforeEach void reset(){jdbc.execute("truncate table financial_intent_command,financial_intent_event,financial_intent_revision,financial_intent");}
 @Test @WithMockUser(username=C,authorities={"FINANCIAL_INTENT_READ","FINANCIAL_INTENT_WRITE"}) void fullCustomerFlowAndStaffMinimumScope()throws Exception{
  String draft="{\"paymentContinuity\":\"KEEP_ESSENTIAL_PAYMENTS\",\"explanationMode\":\"SIMPLE_TEXT\",\"helpCondition\":\"ON_CUSTOMER_REQUEST\",\"shareScopes\":[\"PAYMENT_PREFERENCE\",\"HELP_CONDITION\"]}";
  MvcResult created=mvc.perform(post("/api/v1/customers/{customerId}/financial-intents/drafts",C).header("Idempotency-Key","intent-create-001").contentType(MediaType.APPLICATION_JSON).content(draft)).andExpect(status().isCreated()).andExpect(jsonPath("$.data.status").value("DRAFT")).andExpect(jsonPath("$.data.legallyBinding").value(false)).andExpect(jsonPath("$.data.healthInferenceUsed").value(false)).andReturn();
  String id=json.readTree(created.getResponse().getContentAsByteArray()).at("/data/intentId").asText();
  mvc.perform(post("/api/v1/customers/{customerId}/financial-intents/drafts",C).header("Idempotency-Key","intent-create-001").contentType(MediaType.APPLICATION_JSON).content(draft)).andExpect(status().isCreated()).andExpect(jsonPath("$.data.intentId").value(id));
  mvc.perform(post("/api/v1/customers/{customerId}/financial-intents/{intentId}/approve",C,id).header("Idempotency-Key","intent-approve-invalid").contentType(MediaType.APPLICATION_JSON).content("{\"expectedVersion\":1,\"disclaimerAccepted\":false}")).andExpect(status().isBadRequest());
  String update="{\"expectedVersion\":1,\"paymentContinuity\":\"REVIEW_BEFORE_CHANGE\",\"explanationMode\":\"VOICE_AND_TEXT\",\"helpCondition\":\"ON_REPEATED_CHANGE\",\"shareScopes\":[\"PAYMENT_PREFERENCE\",\"HELP_CONDITION\"]}";
  mvc.perform(put("/api/v1/customers/{customerId}/financial-intents/{intentId}/draft",C,id).header("Idempotency-Key","intent-update-001").contentType(MediaType.APPLICATION_JSON).content(update)).andExpect(status().isOk()).andExpect(jsonPath("$.data.version").value(2));
  mvc.perform(post("/api/v1/customers/{customerId}/financial-intents/{intentId}/approve",C,id).header("Idempotency-Key","intent-approve-001").contentType(MediaType.APPLICATION_JSON).content("{\"expectedVersion\":2,\"disclaimerAccepted\":true}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("APPROVED"));
  mvc.perform(get("/api/v1/customers/{customerId}/continuity-preparation",C)).andExpect(status().isOk()).andExpect(jsonPath("$.data.readiness").value("READY"));
  mvc.perform(get("/api/v1/customers/{customerId}/financial-intents/versions",C)).andExpect(status().isOk()).andExpect(jsonPath("$.data.total").value(3));
  mvc.perform(get("/api/v1/staff/customers/{customerId}/financial-intent-summary",C).with(user("staff").authorities(new org.springframework.security.core.authority.SimpleGrantedAuthority("FINANCIAL_INTENT_SHARED_READ"))))
   .andExpect(status().isOk()).andExpect(jsonPath("$.data.paymentContinuity").value("REVIEW_BEFORE_CHANGE"))
   .andExpect(jsonPath("$.data.explanationMode").doesNotExist()).andExpect(jsonPath("$.data.nonConsentedFieldsExcluded").value(true));
  mvc.perform(get("/api/v1/customers/{customerId}/continuity-preparation",C).with(user("staff").authorities(new org.springframework.security.core.authority.SimpleGrantedAuthority("FINANCIAL_INTENT_SHARED_READ")))).andExpect(status().isForbidden());
  UUID event=jdbc.queryForObject("select event_id from financial_intent_event limit 1",UUID.class);assertThatThrownBy(()->jdbc.update("delete from financial_intent_event where event_id=?",event)).isInstanceOf(DataAccessException.class).hasMessageContaining("append-only");
  mvc.perform(post("/api/v1/customers/{customerId}/financial-intents/{intentId}/revoke",C,id).header("Idempotency-Key","intent-revoke-001").contentType(MediaType.APPLICATION_JSON).content("{\"expectedVersion\":3,\"reason\":\"고객 요청\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("REVOKED"));
 }
}
