package com.alzswell.intent;
import static org.assertj.core.api.Assertions.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.authentication;
import com.alzswell.identity.application.AuthSessionService.AuthenticatedPrincipal;import com.alzswell.identity.application.AuthSessionService.AuthenticatedSession;
import com.fasterxml.jackson.databind.*;import java.util.UUID;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.testcontainers.service.connection.ServiceConnection;import org.springframework.dao.DataAccessException;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.test.context.support.WithMockUser;import org.springframework.test.web.servlet.*;import org.testcontainers.containers.PostgreSQLContainer;import org.testcontainers.junit.jupiter.*;
@SpringBootTest @AutoConfigureMockMvc @Testcontainers(disabledWithoutDocker=true)
class FinancialIntentIntegrationTest {static final String C="SYN_CUSTOMER_FIN_MGMT_001";static final UUID STAFF=UUID.fromString("93000000-0000-0000-0000-000000000099");@Container@ServiceConnection static final PostgreSQLContainer<?> P=new PostgreSQLContainer<>("postgres:17-alpine");@Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate jdbc;
 @BeforeEach void reset(){jdbc.execute("truncate table staff_access_decision_audit_event,staff_access_grant_event,staff_access_grant,financial_intent_command,financial_intent_event,financial_intent_revision,financial_intent");jdbc.update("insert into auth_principal(principal_id,login_id,customer_id,display_name,password_hash,status,created_at,updated_at) select ?,'intent-staff',customer_id,'의향 조회 직원',password_hash,'ACTIVE',now(),now() from auth_principal where login_id='synthetic-customer' on conflict(principal_id) do update set status='ACTIVE',updated_at=now()",STAFF);jdbc.update("insert into auth_principal_role(principal_id,role_code) values(?,'PROTECTION_STAFF') on conflict do nothing",STAFF);jdbc.update("insert into staff_access_grant(grant_id,staff_principal_id,customer_id,purpose_code,scopes,status,granted_by,granted_at,expires_at,idempotency_key_hash,request_hash,row_version) values(?,?,?,'FINANCIAL_INTENT_REVIEW',array['FINANCIAL_INTENT_READ'],'ACTIVE',?,now(),now()+interval '1 day',repeat('e',64),repeat('f',64),1)",UUID.randomUUID(),STAFF,C,STAFF);}
 @Test @WithMockUser(username=C,authorities={"FINANCIAL_INTENT_READ","FINANCIAL_INTENT_WRITE"}) void fullCustomerFlowAndStaffMinimumScope()throws Exception{
  String draft="{\"paymentContinuity\":\"KEEP_ESSENTIAL_PAYMENTS\",\"explanationMode\":\"SIMPLE_TEXT\",\"helpCondition\":\"ON_CUSTOMER_REQUEST\",\"shareScopes\":[\"PAYMENT_PREFERENCE\",\"HELP_CONDITION\"]}";
  MvcResult created=mvc.perform(post("/api/v1/customers/{customerId}/financial-intents/drafts",C).header("Idempotency-Key","intent-create-001").contentType(MediaType.APPLICATION_JSON).content(draft)).andExpect(status().isCreated()).andExpect(jsonPath("$.data.status").value("DRAFT")).andExpect(jsonPath("$.data.legallyBinding").value(false)).andExpect(jsonPath("$.data.healthInferenceUsed").value(false)).andReturn();
  String id=json.readTree(created.getResponse().getContentAsByteArray()).at("/data/intentId").asText();
  mvc.perform(post("/api/v1/customers/{customerId}/financial-intents/drafts",C).header("Idempotency-Key","intent-create-001").contentType(MediaType.APPLICATION_JSON).content(draft)).andExpect(status().isCreated()).andExpect(jsonPath("$.data.intentId").value(id));
  mvc.perform(post("/api/v1/customers/{customerId}/financial-intents/{intentId}/approve",C,id).header("Idempotency-Key","intent-approve-invalid").contentType(MediaType.APPLICATION_JSON).content("{\"expectedVersion\":1,\"disclaimerAccepted\":false}")).andExpect(status().isBadRequest());
  String update="{\"expectedVersion\":1,\"paymentContinuity\":\"REVIEW_BEFORE_CHANGE\",\"explanationMode\":\"VOICE_AND_TEXT\",\"helpCondition\":\"ON_REPEATED_CHANGE\",\"shareScopes\":[\"PAYMENT_PREFERENCE\",\"HELP_CONDITION\"]}";
  mvc.perform(put("/api/v1/customers/{customerId}/financial-intents/{intentId}/draft",C,id).header("Idempotency-Key","intent-update-001").contentType(MediaType.APPLICATION_JSON).content(update)).andExpect(status().isOk()).andExpect(jsonPath("$.data.version").value(2));
  mvc.perform(post("/api/v1/customers/{customerId}/financial-intents/{intentId}/approve",C,id).header("Idempotency-Key","intent-approve-001").contentType(MediaType.APPLICATION_JSON).content("{\"expectedVersion\":2,\"disclaimerAccepted\":true}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("APPROVED"));
  mvc.perform(get("/api/v1/customers/{customerId}/continuity-preparation",C)).andExpect(status().isOk()).andExpect(jsonPath("$.data.readiness").value("READY"));
  mvc.perform(get("/api/v1/customers/{customerId}/financial-intents/versions",C)).andExpect(status().isOk()).andExpect(jsonPath("$.data.total").value(3));
  mvc.perform(get("/api/v1/staff/customers/{customerId}/financial-intent-summary",C).with(staff()))
   .andExpect(status().isOk()).andExpect(jsonPath("$.data.paymentContinuity").value("REVIEW_BEFORE_CHANGE"))
   .andExpect(jsonPath("$.data.explanationMode").doesNotExist()).andExpect(jsonPath("$.data.nonConsentedFieldsExcluded").value(true));
  mvc.perform(get("/api/v1/customers/{customerId}/continuity-preparation",C).with(user("staff").authorities(new org.springframework.security.core.authority.SimpleGrantedAuthority("FINANCIAL_INTENT_SHARED_READ")))).andExpect(status().isForbidden());
  MvcResult secondDraft=mvc.perform(post("/api/v1/customers/{customerId}/financial-intents/drafts",C).header("Idempotency-Key","intent-create-002").contentType(MediaType.APPLICATION_JSON).content(draft)).andExpect(status().isCreated()).andReturn();
  String secondId=json.readTree(secondDraft.getResponse().getContentAsByteArray()).at("/data/intentId").asText();
  mvc.perform(post("/api/v1/customers/{customerId}/financial-intents/{intentId}/approve",C,secondId).header("Idempotency-Key","aaaaaaaa").contentType(MediaType.APPLICATION_JSON).content("{\"expectedVersion\":1,\"disclaimerAccepted\":true}"))
   .andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("FINANCIAL_INTENT_APPROVED_ALREADY_EXISTS"));
  UUID event=jdbc.queryForObject("select event_id from financial_intent_event limit 1",UUID.class);assertThatThrownBy(()->jdbc.update("delete from financial_intent_event where event_id=?",event)).isInstanceOf(DataAccessException.class).hasMessageContaining("append-only");
  mvc.perform(post("/api/v1/customers/{customerId}/financial-intents/{intentId}/revoke",C,id).header("Idempotency-Key","intent-revoke-001").contentType(MediaType.APPLICATION_JSON).content("{\"expectedVersion\":3,\"reason\":\"고객 요청\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("REVOKED"));
 }
 private org.springframework.test.web.servlet.request.RequestPostProcessor staff(){var token=new org.springframework.security.authentication.UsernamePasswordAuthenticationToken(new AuthenticatedPrincipal(STAFF,C),null,java.util.List.of(new org.springframework.security.core.authority.SimpleGrantedAuthority("FINANCIAL_INTENT_SHARED_READ")));token.setDetails(new AuthenticatedSession(UUID.fromString("93000000-0000-0000-0000-000000000098")));return authentication(token);}
}
