package com.alzswell.fx.application;
import static com.alzswell.fx.api.FxResponses.*;import com.alzswell.common.exception.BusinessException;import com.alzswell.fx.api.*;import java.math.*;import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @Transactional(readOnly=true) public class FxQueryService {
 private static final String RATE_SQL="select rate_id,currency,currency_name,unit_amount,base_rate,remittance_send_rate,remittance_receive_rate,cash_buy_rate,cash_sell_rate,quoted_at,data_as_of from fx_rate_snapshot";private final JdbcTemplate jdbc;
 public FxQueryService(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public RateList rates(){List<Rate> items=jdbc.query(RATE_SQL+" order by currency",this::mapRate);return new RateList(items,items.size(),"KRW",true,true,false);}
 public Rate rate(String currency){List<Rate> rows=jdbc.query(RATE_SQL+" where currency=?",this::mapRate,currency);if(rows.size()!=1)throw new BusinessException(FxErrorCode.RATE_NOT_FOUND);return rows.getFirst();}
 public AccountList accounts(String customer){List<Account> items=jdbc.query("select a.account_id,a.institution_id,i.display_name,a.masked_account_number,a.account_name,a.currency,a.balance,a.available_balance,a.status,a.data_as_of from customer_foreign_currency_account_snapshot a join financial_institution i using(institution_id) where a.customer_id=? order by a.currency,a.account_id",(r,n)->new Account(r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getBigDecimal(7),r.getBigDecimal(8),r.getString(9),r.getObject(10,LocalDate.class)),customer);return new AccountList(customer,items,items.size(),true,false);}
 public Simulation simulate(FxRequests.Simulation c){boolean buy="KRW".equals(c.fromCurrency())&&!"KRW".equals(c.toCurrency());boolean sell=!"KRW".equals(c.fromCurrency())&&"KRW".equals(c.toCurrency());if(!buy&&!sell)throw new BusinessException(FxErrorCode.INPUT_INVALID);Rate r=rate(buy?c.toCurrency():c.fromCurrency());BigDecimal applied=buy?r.remittanceSendRate():r.remittanceReceiveRate();BigDecimal converted=buy?c.amount().multiply(r.unitAmount()).divide(applied,2,RoundingMode.DOWN):c.amount().multiply(applied).divide(r.unitAmount(),0,RoundingMode.DOWN);return new Simulation(c.fromCurrency(),c.toCurrency(),c.amount(),applied,r.unitAmount(),converted,buy?"KRW_TO_FOREIGN_REMITTANCE_RATE_V1":"FOREIGN_TO_KRW_REMITTANCE_RATE_V1",r.quotedAt(),false,false,true,false,false);}
 public RemittanceList remittances(String customer){List<Remittance> items=jdbc.query("select remittance_id,source_account_id,destination_country_code,beneficiary_alias,currency,foreign_amount,applied_rate,krw_amount,fee_amount,status,requested_at,completed_at from overseas_remittance_snapshot where customer_id=? order by requested_at desc,remittance_id desc",(r,n)->new Remittance(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getString(3),r.getString(4),r.getString(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getBigDecimal(8),r.getBigDecimal(9),r.getString(10),r.getObject(11,OffsetDateTime.class),r.getObject(12,OffsetDateTime.class)),customer);return new RemittanceList(customer,items,items.size(),true,false,false);}
 private Rate mapRate(java.sql.ResultSet r,int n)throws java.sql.SQLException{return new Rate(r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getBigDecimal(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getBigDecimal(8),r.getBigDecimal(9),r.getObject(10,OffsetDateTime.class),r.getObject(11,LocalDate.class));}
}
