alter table decision_audit
    drop constraint if exists decision_audit_demo_session_id_fkey;

alter table demo_idempotency_record
    alter column idempotency_key type varchar(80);

update demo_idempotency_record
   set idempotency_key = 'legacy-md5:' || md5(operation_key || ':' || idempotency_key);

create or replace function require_demo_capability_hashes()
returns trigger
language plpgsql
as $$
begin
    if new.customer_capability_hash is null
       or new.staff_capability_hash is null
       or new.customer_capability_hash = new.staff_capability_hash then
        raise exception 'new demo sessions require distinct capability hashes';
    end if;
    return new;
end;
$$;

create trigger trg_demo_session_capability_hashes
before insert or update of customer_capability_hash, staff_capability_hash on demo_session
for each row execute function require_demo_capability_hashes();

alter table decision_audit
    add column audit_sequence bigint generated by default as identity,
    add column actor_id varchar(80),
    add column target_type varchar(60),
    add column target_id varchar(120),
    add column before_state varchar(60),
    add column after_state varchar(60),
    add column evidence_hash varchar(80),
    add column request_hash varchar(80),
    add column idempotency_key_hash varchar(80),
    add column previous_event_hash varchar(80),
    add column event_hash varchar(80);

update decision_audit
   set target_type = 'DEMO_SESSION',
       target_id = demo_session_id::text,
       evidence_hash = 'sha256:legacy',
       event_hash = 'sha256:legacy-' || replace(audit_id::text, '-', '')
 where event_hash is null;

alter table decision_audit
    alter column target_type set not null,
    alter column target_id set not null,
    alter column evidence_hash set not null,
    alter column event_hash set not null;

create unique index uq_decision_audit_event_hash
    on decision_audit (event_hash);

create index idx_decision_audit_run_sequence
    on decision_audit (demo_session_id, demo_run_id, audit_sequence);

create or replace function reject_decision_audit_mutation()
returns trigger
language plpgsql
as $$
begin
    raise exception 'decision_audit is append-only';
end;
$$;

create trigger trg_decision_audit_append_only
before update or delete on decision_audit
for each row execute function reject_decision_audit_mutation();

comment on column decision_audit.previous_event_hash is '동일 세션 직전 감사 이벤트 hash';
comment on column decision_audit.event_hash is '이전 hash와 현재 이벤트 canonical payload로 계산한 SHA-256';
