package com.alzswell.fx;
import static org.assertj.core.api.Assertions.assertThatThrownBy;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.testcontainers.service.connection.ServiceConnection;import org.springframework.dao.DataAccessException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.web.servlet.MockMvc;import org.testcontainers.containers.PostgreSQLContainer;import org.testcontainers.junit.jupiter.*;
@SpringBootTest @AutoConfigureMockMvc @Testcontainers(disabledWithoutDocker=true) class FxIntegrationTest {
 static final String CUSTOMER="SYN_CUSTOMER_FIN_MGMT_001";@Container @ServiceConnection static final PostgreSQLContainer<?> POSTGRES=new com.alzswell.test.PgVectorPostgreSqlContainer();@Autowired MockMvc mvc;@Autowired JdbcTemplate jdbc;
 private org.springframework.test.web.servlet.request.RequestPostProcessor read(){return user(CUSTOMER).authorities(()->"FX_READ");}private org.springframework.test.web.servlet.request.RequestPostProcessor sim(){return user(CUSTOMER).authorities(()->"FX_SIMULATE");}
 @Test void readsFiveSafeFxApis()throws Exception{mvc.perform(get("/api/v1/fx/rates").with(read())).andExpect(status().isOk()).andExpect(jsonPath("$.data.total").value(3)).andExpect(jsonPath("$.data.externalProviderCalled").value(false));mvc.perform(get("/api/v1/fx/rates/USD").with(read())).andExpect(status().isOk()).andExpect(jsonPath("$.data.currencyName").value("미국 달러"));mvc.perform(get("/api/v1/customers/{id}/foreign-currency-accounts",CUSTOMER).with(read())).andExpect(status().isOk()).andExpect(jsonPath("$.data.total").value(2)).andExpect(jsonPath("$.data.items[0].maskedAccountNumber").value(org.hamcrest.Matchers.containsString("*")));mvc.perform(post("/api/v1/fx/exchange-simulations").with(sim()).contentType("application/json").content("{\"fromCurrency\":\"KRW\",\"toCurrency\":\"USD\",\"amount\":1406400}" )).andExpect(status().isOk()).andExpect(jsonPath("$.data.convertedAmount").value(1000.00)).andExpect(jsonPath("$.data.exchangeCreated").value(false));mvc.perform(get("/api/v1/customers/{id}/overseas-remittance-history",CUSTOMER).with(read())).andExpect(status().isOk()).andExpect(jsonPath("$.data.total").value(2)).andExpect(jsonPath("$.data.externalActionExecuted").value(false));}
 @Test void ownershipAuthorityAndPairAreEnforced()throws Exception{mvc.perform(get("/api/v1/fx/rates").with(user(CUSTOMER))).andExpect(status().isForbidden());mvc.perform(get("/api/v1/customers/OTHER/foreign-currency-accounts").with(read())).andExpect(status().isForbidden());mvc.perform(post("/api/v1/fx/exchange-simulations").with(sim()).contentType("application/json").content("{\"fromCurrency\":\"USD\",\"toCurrency\":\"EUR\",\"amount\":100}" )).andExpect(status().isBadRequest()).andExpect(jsonPath("$.code").value("FX_SIMULATION_INPUT_INVALID"));}
 @Test void snapshotsAreAppendOnly(){assertThatThrownBy(()->jdbc.update("update fx_rate_snapshot set base_rate=1")).isInstanceOf(DataAccessException.class).hasMessageContaining("append-only");assertThatThrownBy(()->jdbc.update("delete from overseas_remittance_snapshot")).isInstanceOf(DataAccessException.class).hasMessageContaining("append-only");}
}
