package com.alzswell.intent.api;
import com.alzswell.common.api.*;import com.alzswell.common.security.AuditActor;import com.alzswell.intent.application.FinancialIntentService;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.util.UUID;import org.springframework.http.ResponseEntity;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.validation.annotation.Validated;import org.springframework.web.bind.annotation.*;
@RestController @Validated
public class FinancialIntentController {private static final String C="[A-Za-z0-9][A-Za-z0-9_:-]{2,79}";private static final String K="[A-Za-z0-9._:-]+";private final FinancialIntentService s;public FinancialIntentController(FinancialIntentService s){this.s=s;}
 @GetMapping("/api/v1/customers/{customerId}/continuity-preparation") @PreAuthorize("#customerId==authentication.name and hasAuthority('FINANCIAL_INTENT_READ')")
 public ResponseEntity<ApiResponse<FinancialIntentResponses.Preparation>> preparation(@PathVariable @Pattern(regexp=C)String customerId){return ApiResponses.ok("CONTINUITY_PREPARATION_RETRIEVED","금융생활 준비상태와 최신 승인 의향을 조회했습니다.",s.preparation(customerId));}
 @PostMapping("/api/v1/customers/{customerId}/financial-intents/drafts") @PreAuthorize("#customerId==authentication.name and hasAuthority('FINANCIAL_INTENT_WRITE')")
 public ResponseEntity<ApiResponse<FinancialIntentResponses.Intent>> create(@PathVariable @Pattern(regexp=C)String customerId,@RequestHeader("Idempotency-Key")@Size(min=8,max=100)@Pattern(regexp=K)String key,@Valid@RequestBody FinancialIntentRequests.Draft body,Authentication a){return ApiResponses.created("FINANCIAL_INTENT_DRAFT_CREATED","고객 확인 전 금융생활 의향 초안을 생성했습니다.",s.create(customerId,body,key,AuditActor.from(a)));}
 @PutMapping("/api/v1/customers/{customerId}/financial-intents/{intentId}/draft") @PreAuthorize("#customerId==authentication.name and hasAuthority('FINANCIAL_INTENT_WRITE')")
 public ResponseEntity<ApiResponse<FinancialIntentResponses.Intent>> update(@PathVariable @Pattern(regexp=C)String customerId,@PathVariable UUID intentId,@RequestHeader("Idempotency-Key")@Size(min=8,max=100)@Pattern(regexp=K)String key,@Valid@RequestBody FinancialIntentRequests.Update body,Authentication a){return ApiResponses.ok("FINANCIAL_INTENT_DRAFT_UPDATED","금융생활 의향 초안을 수정했습니다.",s.update(customerId,intentId,body,key,AuditActor.from(a)));}
 @PostMapping("/api/v1/customers/{customerId}/financial-intents/{intentId}/approve") @PreAuthorize("#customerId==authentication.name and hasAuthority('FINANCIAL_INTENT_WRITE')")
 public ResponseEntity<ApiResponse<FinancialIntentResponses.Intent>> approve(@PathVariable @Pattern(regexp=C)String customerId,@PathVariable UUID intentId,@RequestHeader("Idempotency-Key")@Size(min=8,max=100)@Pattern(regexp=K)String key,@Valid@RequestBody FinancialIntentRequests.Approve body,Authentication a){return ApiResponses.ok("FINANCIAL_INTENT_APPROVED","고객이 법적 효력 제한을 확인하고 의향을 승인했습니다.",s.approve(customerId,intentId,body,key,AuditActor.from(a)));}
 @GetMapping("/api/v1/customers/{customerId}/financial-intents/versions") @PreAuthorize("#customerId==authentication.name and hasAuthority('FINANCIAL_INTENT_READ')")
 public ResponseEntity<ApiResponse<FinancialIntentResponses.Versions>> versions(@PathVariable @Pattern(regexp=C)String customerId){return ApiResponses.ok("FINANCIAL_INTENT_VERSIONS_RETRIEVED","금융생활 의향의 불변 버전 이력을 조회했습니다.",s.versions(customerId));}
 @PostMapping("/api/v1/customers/{customerId}/financial-intents/{intentId}/revoke") @PreAuthorize("#customerId==authentication.name and hasAuthority('FINANCIAL_INTENT_WRITE')")
 public ResponseEntity<ApiResponse<FinancialIntentResponses.Intent>> revoke(@PathVariable @Pattern(regexp=C)String customerId,@PathVariable UUID intentId,@RequestHeader("Idempotency-Key")@Size(min=8,max=100)@Pattern(regexp=K)String key,@Valid@RequestBody FinancialIntentRequests.Revoke body,Authentication a){return ApiResponses.ok("FINANCIAL_INTENT_REVOKED","승인된 금융생활 의향을 철회했습니다.",s.revoke(customerId,intentId,body,key,AuditActor.from(a)));}
 @GetMapping("/api/v1/staff/customers/{customerId}/financial-intent-summary") @PreAuthorize("hasAuthority('FINANCIAL_INTENT_SHARED_READ')")
 public ResponseEntity<ApiResponse<FinancialIntentResponses.StaffSummary>> staff(@PathVariable @Pattern(regexp=C)String customerId){return ApiResponses.ok("FINANCIAL_INTENT_SHARED_SUMMARY_RETRIEVED","고객이 공유에 동의한 최신 의향 항목만 조회했습니다.",s.staff(customerId));}
}
