package com.alzswell.fx.api;
import com.alzswell.common.api.*;import com.alzswell.fx.application.FxQueryService;import io.swagger.v3.oas.annotations.Operation;import jakarta.validation.Valid;import jakarta.validation.constraints.Pattern;import org.springframework.http.ResponseEntity;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.validation.annotation.Validated;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1") @Validated public class FxController {
 private static final String CUSTOMER="^[A-Za-z0-9][A-Za-z0-9_:-]{2,79}$";private final FxQueryService service;public FxController(FxQueryService service){this.service=service;}
 @GetMapping("/fx/rates") @Operation(summary="안심은행 합성 환율표 조회",description="고정 지연 환율만 제공하고 외부 환율망을 호출하지 않습니다.") @PreAuthorize("hasAuthority('FX_READ')") public ResponseEntity<ApiResponse<FxResponses.RateList>> rates(){return ApiResponses.ok("FX_RATES_RETRIEVED","합성 환율표를 조회했습니다.",service.rates());}
 @GetMapping("/fx/rates/{currency}") @Operation(summary="통화별 합성 환율 조회") @PreAuthorize("hasAuthority('FX_READ')") public ResponseEntity<ApiResponse<FxResponses.Rate>> rate(@PathVariable @Pattern(regexp="USD|JPY|EUR") String currency){return ApiResponses.ok("FX_RATE_RETRIEVED","합성 통화 환율을 조회했습니다.",service.rate(currency));}
 @GetMapping("/customers/{customerId}/foreign-currency-accounts") @Operation(summary="고객 합성 외화계좌 조회") @PreAuthorize("#customerId==authentication.name and hasAuthority('FX_READ')") public ResponseEntity<ApiResponse<FxResponses.AccountList>> accounts(@PathVariable @Pattern(regexp=CUSTOMER) String customerId){return ApiResponses.ok("FX_ACCOUNTS_RETRIEVED","마스킹된 합성 외화계좌를 조회했습니다.",service.accounts(customerId));}
 @PostMapping("/fx/exchange-simulations") @Operation(summary="실행 없는 합성 환전 모의계산",description="KRW와 지원 외화 사이 금액만 계산하고 환전을 생성하지 않습니다.") @PreAuthorize("hasAuthority('FX_SIMULATE')") public ResponseEntity<ApiResponse<FxResponses.Simulation>> simulate(@Valid @RequestBody FxRequests.Simulation command){return ApiResponses.ok("FX_EXCHANGE_SIMULATED","실제 환전 없이 합성 금액을 계산했습니다.",service.simulate(command));}
 @GetMapping("/customers/{customerId}/overseas-remittance-history") @Operation(summary="고객 합성 해외송금 이력 조회") @PreAuthorize("#customerId==authentication.name and hasAuthority('FX_READ')") public ResponseEntity<ApiResponse<FxResponses.RemittanceList>> remittances(@PathVariable @Pattern(regexp=CUSTOMER) String customerId){return ApiResponses.ok("OVERSEAS_REMITTANCES_RETRIEVED","합성 해외송금 이력을 조회했습니다.",service.remittances(customerId));}
}
